# Generated by Django 4.2.3 on 2023-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
